### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by Marawanbakr** [Marawanbakr/font-awesome#1]
I cant using font-awesome and I have a problem  in the photos
...thanks

**Comment by ahmedyounes** [comment]
starting now

**Comment by ahmedyounes** [comment]
<img width="1041" alt="Screen Shot 2020-08-12 at 5 09 15 AM" src="https://user-images.githubusercontent.com/28989583/89970838-fa6f0000-dc59-11ea-81d3-d8f3b21feaf8.png">
is it ok like this ?

**Comment by ahmedyounes** [comment]
done!

**Comment by Marawanbakr** [comment]
DONE
